version: '3.9'

services:
  app:
    build: .
    container_name: studio.hypnagogia
    env_file:
      - .env
    volumes:
      - ./backend/data:/app/backend/data
    networks:
      - hypnagogia

networks:
  hypnagogia:
    external: true
